name: Read core varlues

# Only trigger on push and contains a change in a folder under operations/core
on:
  push:
    paths:
      - "operations/core/**"
  workflow_dispatch:

env:
  RG_HELLO: ${{ secrets.RG_HELLO }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: ./operations/core
        run: npm install
      - name: Pulumi up
        working-directory: ./operations/core
        run: pulumi up -y -s dev
